In [7]:
import numpy as np

In [8]:
from numpy import *

In [9]:
a=np.array([1,2,3,4,5])

In [10]:
a

array([1, 2, 3, 4, 5])

In [11]:
type(a)

numpy.ndarray

In [12]:
a.ndim

1

In [44]:
c=np.array([[4,5,8,9],[6,7,3,2]],dtype=float)
c

array([[4., 5., 8., 9.],
       [6., 7., 3., 2.]])

In [41]:
c[0][1]

5.0

In [45]:
data=np.array([1,2,3,4,5,6])

In [46]:
c.shape

(2, 4)

In [55]:
data=data.reshape(2,3)
data

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
data.shape

(2, 3)

In [53]:
data.ndim

2

In [57]:
type(data)

numpy.ndarray

In [66]:
data[0]

array([1, 2, 3])

In [72]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [76]:
data1=np.array(np.arange(20,100))
data1

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
       71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87,
       88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [77]:
data1=np.array(np.arange(20,100,2))
data1

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52,
       54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86,
       88, 90, 92, 94, 96, 98])

In [114]:
data=np.arange(1,4)
data=np.array([data,data**2,data*3])
data

array([[1, 2, 3],
       [1, 4, 9],
       [3, 6, 9]])

In [ ]:
data[0][1]=

In [100]:
data=np.multiply.accumulate([1,2,2])
data

array([1, 2, 4], dtype=int32)

In [101]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [103]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [104]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [109]:
data.fill(5)
data

array([5, 5, 5])

In [115]:
data.nonzero()

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [111]:
help(data.nonzero)

Help on built-in function nonzero:

nonzero(...) method of numpy.ndarray instance
    a.nonzero()
    
    Return the indices of the elements that are non-zero.
    
    Refer to `numpy.nonzero` for full documentation.
    
    See Also
    --------
    numpy.nonzero : equivalent function



In [116]:
data.shape

(3, 3)

In [117]:
data.max()

9

In [118]:
data.min()

1

In [139]:
ar1=np.array([[1,2,3],[9,3,4]])
ar2=np.array([[4,5],[7,8],[9,9]])


In [140]:
np.dot(ar1,ar2)

array([[ 45,  48],
       [ 93, 105]])

In [141]:
np.dot(ar1,ar1.transpose())

array([[ 14,  27],
       [ 27, 106]])

In [151]:
a=10
b=np.array([[1,2,3],[2,4,6],[1,4,9]])
c=np.array([[1,4],[2,5],[3,6]])
a*np.dot(b,c)


array([[140, 320],
       [280, 640],
       [360, 780]])

In [153]:
z=np.array([[1,2,3],[2,4,6],[1,4,9]])
y=np.array([[1,4,9],[2,8,5],[3,6,1]])
np.divide(z,y)

array([[1.        , 0.5       , 0.33333333],
       [1.        , 0.5       , 1.2       ],
       [0.33333333, 0.66666667, 9.        ]])

In [168]:
a=np.loadtxt("C:/Users/admin/Desktop/ML/a.txt",delimiter=',' )
a

array([[1., 2.],
       [2., 3.],
       [4., 5.]])

In [178]:
h=100
a=np.loadtxt("C:/Users/admin/Desktop/ML/a.txt",delimiter=',' )
b=np.loadtxt("C:/Users/admin/Desktop/ML/b.txt",delimiter=',' )
h*np.dot(a,b)

array([[ 6700.,  8200.,  4500.,  6000.],
       [ 7000.,  8700.,  5100.,  6800.],
       [ 7600.,  9700.,  6300.,  8400.],
       [ 7900., 10200.,  6900.,  9200.],
       [ 8200., 10700.,  7500., 10000.]])